language: generic
jobs:
  include:
    - name: "2.18.5:33fbad18c814e13bd7ba2053525d8959fee437d1"
      env: LIBDLT_VERSION=33fbad18c814e13bd7ba2053525d8959fee437d1
    - name: "2.18.6"
      env: LIBDLT_VERSION=v2.18.6

services:
  - docker

before_script:
  - make build-image LIBDLT_VERSION=${LIBDLT_VERSION}

script:
  - make lint TAG=${LIBDLT_VERSION}
  - make unit-test TAG=${LIBDLT_VERSION}
